# Ingress rules
ingress:
  - hostname: yourdomain.com
    service: http://localhost:80
  - hostname: www.yourdomain.com
    service: http://localhost:80
  - hostname: api.yourdomain.com
    service: http://localhost:8000
  - hostname: admin.yourdomain.com
    service: http://localhost:8080
  - service: http_status:404

# Settings
warp-routing:
  enabled: false
loglevel: info
logfile: /var/log/cloudflared.log
EOF